### ISSUE TITLE
seata1.6.1 store.mode:file Rollback branch transaction fail and stop retry 后面一直被holding,提示get global lock fail

### ISSUE THREAD

**Issue by junchangpeng** [apache/incubator-seata#7068] opened 2024-12-23 02:15 UTC
### Ⅰ. Issue Description
store.mode=file
store.lock.mode=file
store.session.mode=file
时不时会出现LockConflictException: get global lock fail
清楚undo_log没效果，每次都要重启seata

### Ⅱ. Describe what happened

seata
```
2024-12-23 08:44:07.096  INFO --- [                  Thread-89027] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = 10.178.163.76:8091:6810041594698037397, branchId = 6810041594698037398, resourceId = jdbc:mysql://192.168.xx.xxx:3306/srm_sit ,lockKeys = purchase_enquiry_head:1870993513908887554

2024-12-23 08:44:07.972  INFO --- [  ServerHandlerThread_1_49_500] i.s.s.session.AbstractSessionManager     : xid:10.178.163.76:8091:6810041594698037397 fail end, transaction:GlobalSession{xid='10.178.163.76:8091:6810041594698037397', transactionId=6810041594698037397, status=RollbackFailed, applicationId='srm-inquiry', transactionServiceGroup='default_tx_group', transactionName='default', timeout=120000, beginTime=1734914647042, applicationData='null', lazyLoadBranch=false, active=false, branchSessions=[BR:6810041594698037398/6810041594698037397], globalSessionLock=io.seata.server.session.GlobalSession$GlobalSessionLock@32af5edf, lifecycleListeners=[io.seata.server.storage.file.session.FileSessionManager@4f7bb2aa]}
2024-12-23 08:44:07.972 ERROR --- [  ServerHandlerThread_1_49_500] io.seata.server.coordinator.DefaultCore  : Rollback branch transaction fail and stop retry, xid = 10.178.163.76:8091:6810041594698037397 branchId = 6810041594698037398

后面一直holding

2024-12-23 09:18:34.860  INFO --- [                  Thread-92500] io.seata.core.lock.AbstractLocker        : Global lock on [purchase_enquiry_head:1870993513908887554] is holding by 6810041594698037398
2024-12-23 09:18:34.866 ERROR --- [                  Thread-92500] i.s.c.e.AbstractExceptionHandler         : this request cannot acquire global lock, you can let Seata retry by setting config [client.rm.lock.retryPolicyBranchRollbackOnConflict] = false or manually retry by yourself. request:


应用报错
Caused by: io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:10.178.163.76:8091:6810041594698048625, lockKeys:purchase_enquiry_head:1870993513908887554




```
undo_log 表
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/4454bf6b-1454-44fa-8827-be5b09daf13f" />

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):1.8
- Seata client/server version:  1.6.1
- Database version:mysql 5.7
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment] 2024-12-23 02:18
请查看rm侧，什么原因导致回滚失败。对于回滚失败的事务重启后只是删除和释放锁，而不正常运行时对于failed标记的事务不会进行重试。
Please check the RM side to identify the reason for the rollback failure. For transactions that fail to roll back, after a restart, only the locks are deleted and released, but for transactions marked as failed, no retry will be performed during normal operation

**Comment by junchangpeng** [comment] 2024-12-23 03:10
> 请查看rm侧，什么原因导致回滚失败。对于回滚失败的事务重启后只是删除和释放锁，而不正常运行时对于failed标记的事务不会进行重试。 Please check the RM side to identify the reason for the rollback failure. For transactions that fail to roll back, after a restart, only the locks are deleted and released, but for transactions marked as failed, no retry will be performed during normal operation

目前一时没法定位RM那里出了问题，有什么手动方式处理，不需要重启seata

**Comment by funky-eyes** [comment] 2024-12-23 03:26
估计是被脏写了，file和raft模式只能重启解决，db redis之类的可以改库里的状态
It is estimated that it was dirty. The file and raft modes can only be restarted to solve the problem. Db redis and the like can change the state of the library.

**Comment by junchangpeng** [comment] 2024-12-23 03:37
> 估计是被脏写了，file和raft模式只能重启解决，db redis之类的可以改库里的状态 It is estimated that it was dirty. The file and raft modes can only be restarted to solve the problem. Db redis and the like can change the state of the library.

```
2024-12-23 08:44:24.291 [empty#0 on NoUser] [rpcDispatch_RMROLE_1_3_4] INFO  io.seata.rm.datasource.DataSourceManager:43 - branchRollback failed. branchType:[AT], xid:[10.178.163.76:8091:6810041594698037397], branchId:[6810041594698037398], resourceId:[jdbc:mysql://192.xxx.xx.xxx:3306/srm_sit], applicationData:[null]. reason:[Branch session rollback failed because of dirty undo log, please delete the relevant undolog after manually calibrating the data. xid = 10.178.163.76:8091:6810041594698037397 branchId = 6810041594698037398]
```
RM找到这个错误，可有什么方式能解决这个BUG？升级seata版本？

**Comment by junchangpeng** [comment] 2024-12-23 03:53
```
2024-12-23 08:44:23.829 [7be45f2d914fb599fcba4fe33b4e1fba on 3248034_23010416] [http-nio-23000-exec-7] WARN  c.e.m.d.s.impl.PurchaseRequestItemServiceImpl:176 - SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@8db1e11] was not registered for synchronization because DataSource is not transactional
```
是否跟这个WARN有关？

**Comment by funky-eyes** [comment] 2024-12-23 05:39
跟这个warn没关系，这个不是bug，是你的数据被脏写了，仔细看2024-12-23 08:44:24.291 前面的日志，根据这个branchid自行看下，提示的英文翻译下就知道意思，为什么认为这是个bug？
It has nothing to do with this warning. This is not a bug; your data has been dirty written. Carefully review the logs before 2024-12-23 08:44:24.291, check the branchid as suggested, and the English translation of the message will give you the meaning. Why do you think this is a bug?

**Comment by junchangpeng** [comment] 2024-12-23 07:01
> 跟这个warn没关系，这个不是bug，是你的数据被脏写了，仔细看2024-12-23 08:44:24.291 前面的日志，根据这个branchid自行看下，提示的英文翻译下就知道意思，为什么认为这是个bug？ It has nothing to do with this warning. This is not a bug; your data has been dirty written. Carefully review the logs before 2024-12-23 08:44:24.291, check the branchid as suggested, and the English translation of the message will give you the meaning. Why do you think this is a bug?

这只是我的一个看法，数据脏读了，seata这边不至于一直持有锁着，有个超时时间到了不会释放吗？目前只能重启seata释放锁，后续业务才能走下

**Closed as completed** 2024-12-23 11:01 UTC
